### ISSUE TITLE
Blank line in README.rst leading to strange linebreak in rendered version.

### ISSUE THREAD

**Issue by gimbo** [Twangist/prelogging#2]
Line 210, the blank line in the following section, leads to a strange linebreak in the rendered output:

```
**Note**: Already these requirements exceed the abilities of
`logging.basicConfig() <https://docs.python.org/3/library/logging.html#logging.basicConfig>`_

when used to configure logging in a single call. Used in that manner, the function
can create a stream handler or a file handler, but not both.
```

**Comment by Twangist** [comment]
Thanks for your prompt feedback, apologies for my tardy reply. I thought I was getting emailed about notifications -- apparently not. Good catches - both this and your other observation. I did fix both in the next (?) release; in any case, they're fixed now.
